name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (Release)
        run: |
          # Your build commands here (e.g., MSBuild, dotnet build, etc.)
          echo "Building in Release mode..."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: ./bin/Release/
